namespace Mbk.Discord.Enums;

[Flags]
public enum UserFlags
{
	STAFF = 0,
	PARTNER = 1,
	HYPESQUAD = 2,
	BUG_HUNTER_LEVEL_1 = 3,
	HYPESQUAD_ONLINE_HOUSE_1 = 6,
	HYPESQUAD_ONLINE_HOUSE_2 = 7,
	HYPESQUAD_ONLINE_HOUSE_3 = 8,
	PREMIUM_EARLY_SUPPORTER = 9,
	TEAM_PSEUDO_USER = 10,
	BUG_HUNTER_LEVEL_2 = 14,
	VERIFIED_BOT = 16,
	VERIFIED_DEVELOPER = 17,
	CERTIFIED_MODERATOR = 18,
	BOT_HTTP_INTERACTIONS = 19,
	ACTIVE_DEVELOPER = 22
}
